### ISSUE TITLE
Create `./data/ibo-ground-truth` to store PNG images

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo-ocr#2]
## Background
According to the [design doc](https://docs.google.com/document/d/1WlPgMkrZ506MzR6EfpCUdRsdmo0qnnLId0KQ3kDu03Q/edit#heading=h.cd6futwgfm8c) we want to create a new directory that's responsible for saving all of our images

## Ideal Solution
Create a new directory at the path `./data/ibo-ground-truth` that will contain **.png** images of books that we will use as training data

**Comment by bontusss** [comment]
Assign me

**Comment by Danimoz** [comment]
Chief I Don already do am
